# Generated by Django 5.2.17 on 2026-08-28 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="tracks/%Y/%m/")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("upload", "Uploaded"),
                            ("tts", "Text-to-Speech"),
                            ("licensed_import", "Licensed Import"),
                            ("youtube_authorized", "YouTube (Authorized)"),
                            ("edited", "Edited"),
                            ("mixed", "Mixed"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("format", models.CharField(blank=True, default="mp3", max_length=10)),
                ("rights_confirmed", models.BooleanField(default=False)),
                ("rights_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("license_info", models.TextField(blank=True, default="")),
                (
                    "tts_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Original text used for TTS generation",
                    ),
                ),
                (
                    "tts_language",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_tracks",
                        to="tracks.track",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tracks", to="tracks.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tracks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="YouTubeImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_url", models.URLField(max_length=500)),
                ("video_id", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=500)),
                (
                    "channel_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "video_duration",
                    models.FloatField(
                        blank=True, help_text="Video duration in seconds", null=True
                    ),
                ),
                ("rights_confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("license_info", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_import",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "db_table": "youtube_imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
